/**
 * The specific prefix used for all logs generated by this library.
 * This makes it easy for developers to filter logs in the console (e.g., in Flipper or Logcat).
 */
const TAG = '[QPMTX-A11Y]';

/**
 * Service responsible for standardized logging across the library.
 * It enforces a consistent tag prefix and handles log levels.
 */
export const LoggerService = {
  /**
   * Logs an informational message.
   * Usually used for debugging flows (e.g., "Screen reader changed to ON").
   * @param {string} message - The primary message to log.
   * @param {...unknown[]} args - Additional data or objects to print.
   */
  info: (message: string, ...args: unknown[]): void => {
    // We strictly use console.log for info
    console.log(`${TAG} ℹ️ ${message}`, ...args);
  },

  /**
   * Logs a warning message.
   * Use this when a heuristic fails or a non-critical accessibility issue is detected
   * (e.g., "Touch target is 40px, but minimum is 44px").
   * @param {string} message - The warning message.
   * @param {...unknown[]} args - Additional context.
   */
  warn: (message: string, ...args: unknown[]): void => {
    console.warn(`${TAG} ⚠️ ${message}`, ...args);
  },

  /**
   * Logs a critical error.
   * Use this when an invalid configuration is passed or a critical failure occurs.
   * @param {string} message - The error message.
   * @param {...unknown[]} args - Additional context or Error objects.
   */
  error: (message: string, ...args: unknown[]): void => {
    console.error(`${TAG} ❌ ${message}`, ...args);
  },
};